---
title: "RWorksheet_cabia#3a."
author: "Billy Brendan Cabia"
date: "2024-09-30"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Using VECTORS
# 1.
# a.
```{r}
first_11_letters <- LETTERS[1:11]
first_11_letters
```
# b.
```{r}
odd_number_letters <- LETTERS[seq(1, 26, by=2)]
odd_number_letters
```
# c.
```{r}
vowels <- LETTERS[c(1, 5, 9, 15, 21)] 
vowels   
```
# d.
```{r}
last5_lowercase <- letters[22:26]
last5_lowercase
```
# e.
```{r}
lowercase_15_to_24 <- letters[15:24]
lowercase_15_to_24
```

# 2.
# a.
```{r}
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city
```
# b.
```{r}
temp <- c(42, 39, 34, 34, 30, 27)
temp
```
# c.
```{r}
df_citytemp <- data.frame(city, temp)
df_citytemp
```
# d.
```{r}
names(df_citytemp) <- c("City", "Temperature")
df_citytemp
```
# e.
```{r}
str(df_citytemp)
```
# f.
```{r}
df_citytemp[3:4,]
```
# g.
```{r}
highest_temp_city <- df_citytemp$City[which.max(df_citytemp$Temperature)]
lowest_temp_city <- df_citytemp$City[which.min(df_citytemp$Temperature)]

highest_temp_city
lowest_temp_city
```

# 2.  using MATRICES
# a.
```{r}
mat <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
mat
```
# b.
```{r}
mult <- mat * 2
mult
```
# c.
```{r}
mat[2, ]
```
# d.
```{r}
mat[1:2, 3:4]
```
# e.
```{r}
mat[3, 2:3]
```
# f.
```{r}
mat[ ,4]
```
# g. 
```{r}
rownames(mat) <- c("isa", "dalawa", "tatlo")
colnames(mat) <- c("uno", "dos", "tres", "quatro")
mat
```
# h.
```{r}
dim(mat) <- c(6, 2)
mat
```
# 3. using ARRAYS
# a.
```{r}
arr1 <- rep(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1), 2)
numarray <- array(arr1, dim = c(2, 4, 3))
numarray
# b.
dim(numarray)
# c.
rownames(numarray) <- c("a", "b")
colnames(numarray) <- c("A", "B", "C", "D")
dimnames(numarray)[[3]] <- c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array")

numarray
```


